# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Developer productivity CLI for macOS"
  homepage "https://github.com/sametkarademir/forge"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.5/forge_darwin_amd64.tar.gz"
      sha256 "105144aca3998c38384648dddeb0cb72c491897cb40d0b9dceed59f78af41a55"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.5/forge_darwin_arm64.tar.gz"
      sha256 "c09c5147548f19c282d09d4c8cf778a08d4ffd9b4d8407889c75457be02710d8"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.5/forge_linux_amd64.tar.gz"
      sha256 "9534634e6265328c7014ae18c582e4e96f9bcc72c431fceb6fe4ec21bb9b0b91"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.5/forge_linux_arm64.tar.gz"
      sha256 "81f14f704d00a7802663ff92eda896bb8c1d79d4e6f7473815e06363bf1d6599"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "--version"
  end
end
