# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Developer productivity CLI for macOS"
  homepage "https://github.com/sametkarademir/forge"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.7/forge_darwin_amd64.tar.gz"
      sha256 "6fdf5c0dd4fe1640d760a9b88115652f6ad64a9b874eb8c2b861dd106b38ba55"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.7/forge_darwin_arm64.tar.gz"
      sha256 "d205431225b8cafcfd68f89507bc9bfd1c6106ba59e5a5895528c9d496adfde5"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.7/forge_linux_amd64.tar.gz"
      sha256 "6e1eadddab61179b87e23ca6a7deaaa495f4f687d179f575d2b6af9380390a78"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.7/forge_linux_arm64.tar.gz"
      sha256 "a54dcb673e3171f316621a1263408b24fb023925590d23cccc37213088ddce26"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "--version"
  end
end
