# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "Developer productivity CLI for macOS"
  homepage "https://github.com/sametkarademir/forge"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.8/forge_darwin_amd64.tar.gz"
      sha256 "144e0e0b04d929b2b3016e680dc5d42207482f8a25a6c2d513ac9ee88e4862fc"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.8/forge_darwin_arm64.tar.gz"
      sha256 "434dd3993d7cbd9c3ce7ca1642ee6ecdd9f00c77f626e7312dbda9bf80bad0a8"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.8/forge_linux_amd64.tar.gz"
      sha256 "ec350ec7a7d3ce1348fbb2072cf093ba15ec414a990ad46dab37630a2d9ac069"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sametkarademir/forge/releases/download/v0.1.8/forge_linux_arm64.tar.gz"
      sha256 "92b378b8fe6a1e64029b5e4dcd32193f6c1cc1070a41dcb70afeba1b925e04a8"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "--version"
  end
end
